export const recordings = [
  {
    id: '2026-08-08',
    title: '教育AI新机遇',
    summary: '8月培训开场；教育AI解决方案；智显AI基础（三）；销售+盒子报价',
    date: '2026-08-08',
    time: '13:45',
    url: 'https://meeting.tencent.com/crm/KebxgxAke0',
    phase: '第 6 期',
    featured: true,
  },
  {
    id: '2026-07-31',
    title: '能源项目介绍：内蒙电力',
    summary: '能源项目案例分享开场引导；内蒙电力案例分享；展厅AI系统链路分享；能源行业 AI 解决方案；AI 基础知识',
    date: '2026-07-31',
    time: '13:50',
    url: 'https://meeting.tencent.com/crm/NobdbOqa8a',
    phase: '第 5 期',
  },
  {
    id: '2026-07-24',
    title: '嘉宾代理商论坛讨论连线',
    summary: 'AI时代的场域营销；同益未来教育学社发起人；辽宁明嘉总经理；北京魔力深思总经理',
    date: '2026-07-24',
    time: '13:50',
    url: 'https://meeting.tencent.com/crm/2O1EG0r377',
    phase: '第 4 期',
  },
  {
    id: '2026-07-17',
    title: '学科大模型介绍：AI科普课',
    summary: '科金大厦展厅项目案例；学科大模型案例介绍；智显AI生成大模型技术简介；AI科普课堂；AI销售小课堂：客户洞察',
    date: '2026-07-17',
    time: '13:41',
    url: 'https://meeting.tencent.com/crm/2kna8Z3R07',
    phase: '第 3 期',
  },
  {
    id: '2026-07-10',
    title: '展厅案例分享：吉大正元智脑新标杆',
    summary: '智显机器人AI展厅方案；吉大正元AI智能展示方案介绍；吉大正元智能展厅：定义AI空间“智脑”新标杆；AI销售小课堂：市场嗅觉',
    date: '2026-07-10',
    time: '13:47',
    url: 'https://meeting.tencent.com/crm/2qn1n9G517',
    phase: '第 2 期',
  },
  {
    id: '2026-07-03',
    title: '开营介绍：技术云边端及AI行业趋势介绍，营销及课程预告',
    summary: '公司战略与开营；技术底座与云边端方案；AI行业发展趋势；IN BOX解决方案分享；AI营销智能体极致讲解；案例汇总与后续课程预告',
    date: '2026-07-03',
    time: '13:48',
    url: 'https://meeting.tencent.com/crm/K0JOQxG0b5',
    phase: '第 1 期',
  },
];

// 培训类 PPT 与会议录像放在同一个“会议回放”模块中。
export const presentationReplays = [
  {
    id: 'august-partner-training',
    title: '8月代理商推广培训开营',
    url: 'https://livepad.zbrain.cn/s/pad-msshgszo-f85na7?p=p_b71f5093762c7caa',
    category: '代理商培训',
    cover: 'assets/covers/partner-training.png',
    publishedAt: '2026-08-01',
  },
  {
    id: 'july-partner-training',
    title: '七月代理商培训',
    url: 'https://livepad.zbrain.cn/s/pad-mssoy8ow-1a7vxh?p=p_b71f5093762c7caa',
    category: '代理商培训',
    cover: 'assets/covers/partner-training.png',
    publishedAt: '2026-07-01',
  },
  {
    id: 'zhixian-ai-training-camp',
    title: '智显AI训战营',
    url: 'https://livepad.zbrain.cn/s/pad-mssqxzql-3f64jp?p=p_b71f5093762c7caa',
    category: '训战课程',
    cover: 'assets/covers/partner-training.png',
  },
  {
    id: 'ai-partner-training-camp-welcome-speech',
    title: 'AI代理商训战营欢迎演讲',
    url: 'https://livepad.zbrain.cn/s/pad-mst0wasr-3cq6h0?p=p_b71f5093762c7caa',
    category: '训战课程',
    cover: 'assets/covers/partner-training.png',
  },
];

// 智能方案讲解按公司、解决方案、案例三类归档。
export const presentations = [
  {
    id: 'zhixian-robot-business-report',
    title: '智显机器人业务汇报',
    url: 'https://www.wanpinghui.com/s/pad-mr6awgyd-hsmvyl?p=p_aafa3c827820c061',
    group: 'company',
    category: '业务汇报',
    cover: 'assets/covers/partner-training.png',
  },
  {
    id: 'ai-showroom-solution',
    title: '智显机器人-AI展厅方案',
    url: 'https://livepad.zbrain.cn/s/pad-msrqboxk-zc248e?p=p_b71f5093762c7caa',
    group: 'solution',
    category: 'AI 展厅',
    cover: 'assets/covers/ai-showroom.png',
  },
  {
    id: 'ai-solution-sales-assistant-01',
    title: 'AI解决方案销售助手01',
    url: 'https://livepad.zbrain.cn/s/pad-mssqel9k-ch3qwm?p=p_ad1c531970069223',
    group: 'solution',
    category: '销售工具',
    cover: 'assets/covers/partner-training.png',
  },
  {
    id: 'smart-space-technology-solution',
    title: '智能空间技术解决方案',
    url: 'https://livepad.zbrain.cn/s/pad-msrhe7lg-3m9wpv?p=p_ad1c531970069223',
    group: 'solution',
    category: '空间方案',
    cover: 'assets/covers/ai-showroom.png',
  },
  {
    id: 'zbrain-aigc-business-solution',
    title: 'ZBrain智显AIGC业务解决方案',
    url: 'https://livepad.zbrain.cn/s/pad-msssttj1-va9wwn?p=p_ad1c531970069223',
    group: 'solution',
    category: 'AIGC 方案',
    cover: 'assets/covers/digital-media-education.png',
  },
  {
    id: 'digital-media-discipline',
    title: '数字媒体专业学科建设方案',
    url: 'https://livepad.zbrain.cn/s/pad-mssgu0n6-poc3iu?p=p_b71f5093762c7caa',
    group: 'solution',
    category: '专业建设',
    cover: 'assets/covers/digital-media-education.png',
  },
  {
    id: 'multi-screen-cloud-edge-device-solution',
    title: '展厅多屏统一联动方案·云边端协同架构',
    url: 'https://www.wanpinghui.com/s/pad-mra1zdh7-5vjsw2?p=p_aafa3c827820c061',
    group: 'solution',
    category: '展厅方案',
    cover: 'assets/covers/ai-showroom.png',
  },
  {
    id: 'livepad-education-application',
    title: 'LivePad在教育行业的应用',
    url: 'https://www.wanpinghui.com/s/pad-mrvwbs4e-w2uyws?p=p_380506a6afac002c',
    group: 'solution',
    category: '教育方案',
    cover: 'assets/covers/digital-media-education.png',
  },
  {
    id: 'energy-industry-ai-application-system',
    title: '能源行业AI智能应用体系建设方案',
    url: 'https://www.wanpinghui.com/s/pad-ms3cwntz-dr13rs?p=p_af053f99e1e57109',
    group: 'solution',
    category: '能源方案',
    cover: 'assets/covers/digital-media-education.png',
  },
  {
    id: 'ai-niuhuang-intelligence-sharing',
    title: 'AI牛黄智脑分享',
    url: 'https://www.wanpinghui.com/s/pad-mrabffy6-p0bphq?p=p_aefd5977a06d2aa3',
    group: 'case',
    category: '案例分享',
    cover: 'assets/covers/partner-training.png',
  },
  {
    id: 'kejindasha-ai-native-showcase-case',
    title: '从科金大厦开启 AI 原生展示空间_案例分享',
    url: 'https://livepad.zbrain.cn/s/pad-mssygqtz-ne9keq?p=p_b71f5093762c7caa',
    group: 'case',
    category: '案例分享',
    cover: 'assets/covers/ai-showroom.png',
  },
  {
    id: 'jilin-university-zhengyuan-ai-showroom',
    title: '吉大正元智能展厅定义AI空间智脑新标杆',
    url: 'https://livepad.zbrain.cn/s/pad-mst00xyj-aeetrp?p=p_b71f5093762c7caa',
    group: 'case',
    category: '展厅案例',
    cover: 'assets/covers/ai-showroom.png',
  },
  {
    id: 'spic-inner-mongolia-digital-human-system',
    title: '国家电投内蒙古能源公司指挥中心数字人系统方案',
    url: 'https://www.wanpinghui.com/s/pad-ms7o70tu-ytsckx?p=p_b539669638878317',
    group: 'case',
    category: '能源案例',
    cover: 'assets/covers/digital-media-education.png',
  },
  {
    id: 'yangzhou-cultural-communication-intelligence',
    title: '扬州文化传播智脑',
    url: 'https://www.wanpinghui.com/s/pad-msb308vm-3noxpu?p=p_29397a78b8578d5e',
    group: 'case',
    category: '文旅案例',
    cover: 'assets/covers/partner-training.png',
  },
];
