export const recordings = [
  {
    id: '2026-08-08',
    title: '智显 AI 训战营课程',
    date: '2026-08-08',
    time: '13:45',
    url: 'https://meeting.tencent.com/crm/KebxgxAke0',
    phase: '第 6 期',
    featured: true,
  },
  {
    id: '2026-07-31',
    title: '智显机器人 AI 训战营',
    date: '2026-07-31',
    time: '13:50',
    url: 'https://meeting.tencent.com/crm/NobdbOqa8a',
    phase: '第 5 期',
  },
  {
    id: '2026-07-24',
    title: '智显机器人 AI 训战营',
    date: '2026-07-24',
    time: '13:50',
    url: 'https://meeting.tencent.com/crm/2O1EG0r377',
    phase: '第 4 期',
  },
  {
    id: '2026-07-17',
    title: '智显机器人 AI 训战营',
    date: '2026-07-17',
    time: '13:41',
    url: 'https://meeting.tencent.com/crm/2kna8Z3R07',
    phase: '第 3 期',
  },
  {
    id: '2026-07-10',
    title: '智显机器人 AI 训战营',
    date: '2026-07-10',
    time: '13:47',
    url: 'https://meeting.tencent.com/crm/2qn1n9G517',
    phase: '第 2 期',
  },
  {
    id: '2026-07-03',
    title: '智显机器人 AI 训战营',
    date: '2026-07-03',
    time: '13:48',
    url: 'https://meeting.tencent.com/crm/K0JOQxG0b5',
    phase: '第 1 期',
  },
];

// 后续 PPT 按相同格式追加标题和链接即可，页面会自动生成方案窗口。
export const presentations = [
  {
    id: 'august-partner-training',
    title: '8月代理商推广培训开营',
    url: 'https://livepad.zbrain.cn/s/pad-msshgszo-f85na7?p=p_b71f5093762c7caa',
    category: '代理商培训',
    cover: 'assets/covers/partner-training.png',
    publishedAt: '2026-08-01',
  },
  {
    id: 'july-partner-training',
    title: '七月代理商培训',
    url: 'https://livepad.zbrain.cn/s/pad-mssoy8ow-1a7vxh?p=p_b71f5093762c7caa',
    category: '代理商培训',
    cover: 'assets/covers/partner-training.png',
    publishedAt: '2026-07-01',
  },
  {
    id: 'ai-solution-sales-assistant-01',
    title: 'AI解决方案销售助手01',
    url: 'https://livepad.zbrain.cn/s/pad-mssqel9k-ch3qwm?p=p_ad1c531970069223',
    category: '销售工具',
    cover: 'assets/covers/partner-training.png',
  },
  {
    id: 'smart-space-technology-solution',
    title: '智能空间技术解决方案',
    url: 'https://livepad.zbrain.cn/s/pad-msrhe7lg-3m9wpv?p=p_ad1c531970069223',
    category: '空间方案',
    cover: 'assets/covers/ai-showroom.png',
  },
  {
    id: 'zhixian-ai-training-camp',
    title: '智显AI训战营',
    url: 'https://livepad.zbrain.cn/s/pad-mssqxzql-3f64jp?p=p_b71f5093762c7caa',
    category: '训战课程',
    cover: 'assets/covers/partner-training.png',
  },
  {
    id: 'zbrain-aigc-business-solution',
    title: 'ZBrain智显AIGC业务解决方案',
    url: 'https://livepad.zbrain.cn/s/pad-msssttj1-va9wwn?p=p_ad1c531970069223',
    category: 'AIGC 方案',
    cover: 'assets/covers/digital-media-education.png',
  },
  {
    id: 'ai-showroom-solution',
    title: '智显机器人-AI展厅方案',
    url: 'https://livepad.zbrain.cn/s/pad-msrqboxk-zc248e?p=p_b71f5093762c7caa',
    category: 'AI 展厅',
    cover: 'assets/covers/ai-showroom.png',
  },
  {
    id: 'digital-media-discipline',
    title: '数字媒体专业学科建设方案',
    url: 'https://livepad.zbrain.cn/s/pad-mssgu0n6-poc3iu?p=p_b71f5093762c7caa',
    category: '专业建设',
    cover: 'assets/covers/digital-media-education.png',
  },
  {
    id: 'kejindasha-ai-native-showcase-case',
    title: '从科金大厦开启 AI 原生展示空间_案例分享',
    url: 'https://livepad.zbrain.cn/s/pad-mssygqtz-ne9keq?p=p_b71f5093762c7caa',
    category: '案例分享',
    cover: 'assets/covers/ai-showroom.png',
  },
  {
    id: 'jilin-university-zhengyuan-ai-showroom',
    title: '吉大正元智能展厅定义AI空间智脑新标杆',
    url: 'https://livepad.zbrain.cn/s/pad-mst00xyj-aeetrp?p=p_b71f5093762c7caa',
    category: '案例分享',
    cover: 'assets/covers/ai-showroom.png',
  },
  {
    id: 'ai-partner-training-camp-welcome-speech',
    title: 'AI代理商训战营欢迎演讲',
    url: 'https://livepad.zbrain.cn/s/pad-mst0wasr-3cq6h0?p=p_b71f5093762c7caa',
    category: '训战课程',
    cover: 'assets/covers/partner-training.png',
  },
];
